dubbo:
  registries:
    shanghai:
      address: nacos://192.168.56.100:8848
      timeout: 30s
      group: shanghai
  protocols:
    triple:
      name: tri
      port: 20000
  provider:
    services:
      SearchService:
        interface: org.apache.dubbo.Search
        group: search
        version: 1.0.0
      ModelService:
        interface: org.apache.dubbo.Model
        group: model
        version: 1.0.0
  consumer:
    check: false
    references:
      SearchClientImpl:
        interface: org.apache.dubbo.Search
        group: search
        version: 1.0.0
      ModelClientImpl:
        interface: org.apache.dubbo.Model
        group: model
        version: 1.0.0
  shutdown:
    internal-signal: false